# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4187a65d95d9fd5fc24ea728ca96ab9ae5617f768fffddf358f9b05471f0f3994cb9260e53da3c70e1427e87dfa26940faa6beb8476bf37683b374225d654011

test:
  secret_key_base: e9607db54fe0c61a1837fe7635c7bc3d4014847cae589ee4aab9e1ae32a81a7776e3928f8cef7dccaf251f90473c2b96bd0b1459bab0ad7ea97c8360204408c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
